kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openwebui
  namespace: ollama-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeMode: Filesystem