apiVersion: velero.io/v1
kind: Backup
metadata:
  name: craig-backup-test
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  hooks: {}
  includedNamespaces:
  - test-oadp
  storageLocation: craig-oadp-dpa-1
  ttl: 720h0m0s