# MinIO cloud-credentials
kind: Secret
apiVersion: v1
metadata:
  name: cloud-credentials
  namespace: openshift-adp
stringData:
  cloud: |
    [default]
    aws_access_key_id=
    aws_secret_access_key=
type: Opaque
