# Azure cloud-credentials
kind: Secret
apiVersion: v1
metadata:
  name: cloud-credentials-azure
  namespace: openshift-adp
stringData:
  cloud: |
    AZURE_STORAGE_ACCOUNT_ACCESS_KEY=<secret>
type: Opaque
