# Test deployment
kind: Namespace
apiVersion: v1
metadata:
  name: craig-test
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: craig-test-pvc
  namespace: craig-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: managed-csi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-app
  namespace: craig-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: random-app
  template:
    metadata:
      labels:
        name: random-app
    spec:
      containers:
      - image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:d8a10938c151a805d74306043901dc786f5f0762599097ed67140e75efce18e0
        imagePullPolicy: IfNotPresent
        name: random
        command:
        - "/bin/bash"
        - "-xc"
        - "sleep 600"
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: content
          mountPath: /mnt/data
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: craig-test-pvc            
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
