apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpd-example-route-cert
  namespace: httpd-example
spec:
  dnsNames:
  - httpd.apps.vqmpz.dynamic.redhatworkshops.io
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: httpd-example-route-cert
  usages:
  - server auth

