apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: httpd-example
rules:
- apiGroups:
  - ""
  resourceNames:
  - httpd-example-route-cert
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
