kind: Job
apiVersion: batch/v1
metadata:
  name: central-secret-automation-job
  namespace: rhacs-operator
spec:
  template:
    spec:
      serviceAccountName: central-secret-automation-sa
      restartPolicy: OnFailure
      containers:
        - name: oc-executor
          image: registry.redhat.io/openshift4/ose-cli:v4.12
          command:
            - /bin/bash
            - -c
            - |
              set -e

              export ROX_PWD_FILE=/data/rox_password
              export CRS_BUNDLE_FILE=/data/crs-bundle.yaml
              export COMPLETE=/data/conplete

              echo "Fetching central admin password"
              echo $(oc -n rhacs-operator get secret central-htpasswd -o jsonpath='{.data.password}' | base64 -d) > ${ROX_PWD_FILE}

              echo "Waiting for CRS bundle ..."
              while ! [ -f ${COMPLETE} ]
              do
                sleep 10
              done

              echo "${CRS_BUNDLE_FILE} bundle has been created"

              echo "Appling CRS bundle to the cluster"
              oc -n rhacs-operator apply -f ${CRS_BUNDLE_FILE}

              rm -fr /data/*

              echo "Complete"

          volumeMounts:
            - name: data
              mountPath: /data
        - name: roxctl-executor
          image: registry.redhat.io/advanced-cluster-security/rhacs-roxctl-rhel9:4.11.1-1
          command:
            - /bin/bash
            - -c
            - |
              set -e

              export ROX_PWD_FILE=/data/rox_password
              export CRS_BUNDLE_FILE=/data/crs-bundle.yaml
              export COMPLETE=/data/conplete

              echo "Waiting for central admin password"
              while ! [ -f ${ROX_PWD_FILE} ]
              do
                sleep 10
              done

              echo "${ROX_PWD_FILE} has been created"

              export ROX_PASSWORD=$(cat ${ROX_PWD_FILE})
              export ROX_CENTRAL_ADDRESS="central.rhacs-operator.svc.cluster.local.:443"

              echo "Generating cluster authentication bundle"
              
              roxctl --endpoint ${ROX_CENTRAL_ADDRESS} --password="${ROX_PASSWORD}" --insecure-skip-tls-verify=false \
                central crs generate gitops-secured-cluster \
                --output ${CRS_BUNDLE_FILE}

              #cat ${CRS_BUNDLE_FILE}
              touch ${COMPLETE}

              echo "Complete"

          volumeMounts:
            - name: data
              mountPath: /data              
      volumes:
        - name: data
          emptyDir: {}
