kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: central-secret-automation
subjects:
  - kind: ServiceAccount
    name: central-secret-automation-sa
    namespace: rhacs-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: central-secret-automation
