FROM registry.access.redhat.com/ubi8/ubi:latest 

#COPY /usr/local/bin/oc-mirror /usr/bin/oc-mirror

RUN yum install -y podman skopeo curl jq wget &&\
    yum clean all &&\
    rm -rf /var/cache/yum &&\
    wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz &&\
    wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/oc-mirror.tar.gz &&\
    tar xzvf openshift-client-linux.tar.gz -C /usr/bin/ &&\
    tar xzvf oc-mirror.tar.gz -C /usr/bin/ &&\
    chmod +x /usr/bin/oc &&\
    chmod +x /usr/bin/oc-mirror &&\
    rm -fr openshift-client-linux.tar.gz &&\
    rm -fr openshift-mirror.tar.gz &&\
    mkdir -p /root/.docker/ 

CMD ["/usr/bin/bash"]
