apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: build-and-deploy
  name: build-and-deploy-ojyq4z
#  namespace: pipelines-tutorial
  namespace: pipeline-tutorial
spec:
  params:
  - name: deployment-name
    value: pipelines-vote-api
  - name: git-url
#    value: https://github.com/openshift/pipelines-vote-api.git
    value: https://github.com/crscottau/pipelines-vote-api.git
  - name: git-revision
    value: master
  - name: IMAGE
    value: quay-registry-quay-quay.apps.pfnjv.dynamic.redhatworkshops.io/pipeline-tutorial/pipelines-vote-api
#    value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/pipelines-vote-api
  - name: TLS_VERIFY
    value: 'false'
  pipelineRef:
    name: build-and-deploy
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: source-pvc