apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: build-and-deploy
  name: build-and-deploy-ojyq4z
  namespace: pipelines-tutorial
spec:
  params:
  - name: deployment-name
    value: pipelines-vote-api
  - name: git-url
    value: https://github.com/openshift/pipelines-vote-api.git
  - name: git-revision
    value: pipelines-1.17
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/pipelines-vote-api
  pipelineRef:
    name: build-and-deploy
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: source-pvc