apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: quay-backup
  namespace: quay
spec:
  cluster:
    name: quay-postgres-cluster-01
    namespace: quay
  immediate: true
  schedule: '0 30 */6 * * *'
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io