#
# Service account and cluster role binding with permissions to control the failover
#
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub-cluster-failover-common-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - 'cluster.open-cluster-management.io'
    resources:
      - 'restores'
      - 'backupschedules'
      - 'managedclusters'
  - verbs:
      - '*'
    apiGroups:
      - 'velero.io'
    resources:
      - 'restores'
      - 'backups'
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: hub-cluster-failover-common-sa
  namespace: open-cluster-management-backup
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub-cluster-failover-common-crb
subjects:
  - kind: ServiceAccount
    name: hub-cluster-failover-common-sa
    namespace: open-cluster-management-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hub-cluster-failover-common-role
