apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nfs-client-provisioner"},"name":"nfs-client-provisioner","namespace":"nfs-provisioner"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nfs-client-provisioner"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"nfs-client-provisioner"}},"spec":{"containers":[{"env":[{"name":"NFS_SERVER","value":"192.168.123.20"},{"name":"NFS_PATH","value":"/"},{"name":"PROVISIONER_NAME","value":"k8s-sigs.io/nfs-subdir-external-provisioner"}],"image":"registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2","name":"nfs-client-provisioner","volumeMounts":[{"mountPath":"/persistentvolumes","name":"nfs-client-root"}]}],"serviceAccountName":"nfs-client-provisioner","volumes":[{"name":"nfs-client-root","nfs":{"path":"/","server":"192.168.123.20"}}]}}}}
  creationTimestamp: "2025-02-18T21:59:50Z"
  generation: 1
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
  namespace: nfs-provisioner
  resourceVersion: "3791717"
  uid: 6061d772-bbd9-4792-b92b-181a561ec711
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nfs-client-provisioner
    spec:
      containers:
      - env:
        - name: NFS_SERVER
          value: 192.168.123.20
        - name: NFS_PATH
          value: /
        - name: PROVISIONER_NAME
          value: k8s-sigs.io/nfs-subdir-external-provisioner
        image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
        imagePullPolicy: IfNotPresent
        name: nfs-client-provisioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /persistentvolumes
          name: nfs-client-root
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nfs-client-provisioner
      serviceAccountName: nfs-client-provisioner
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs-client-root
        nfs:
          path: /
          server: 192.168.123.20
status:
  conditions:
  - lastTransitionTime: "2025-02-18T21:59:51Z"
    lastUpdateTime: "2025-02-18T21:59:51Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-02-18T21:59:51Z"
    lastUpdateTime: "2025-02-18T21:59:51Z"
    message: 'pods "nfs-client-provisioner-76db95d56c-" is forbidden: unable to validate
      against any security context constraint: [provider "anyuid": Forbidden: not
      usable by user or serviceaccount, provider "pipelines-scc": Forbidden: not usable
      by user or serviceaccount, spec.volumes[0]: Invalid value: "nfs": nfs volumes
      are not allowed to be used, provider "restricted": Forbidden: not usable by
      user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user
      or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount,
      provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount,
      provider "logging-scc": Forbidden: not usable by user or serviceaccount, provider
      "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount,
      provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount,
      provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider
      "hostaccess": Forbidden: not usable by user or serviceaccount, provider "lvms-vgmanager":
      Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden:
      not usable by user or serviceaccount, provider "privileged": Forbidden: not
      usable by user or serviceaccount]'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  - lastTransitionTime: "2025-02-18T22:09:52Z"
    lastUpdateTime: "2025-02-18T22:09:52Z"
    message: ReplicaSet "nfs-client-provisioner-76db95d56c" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  unavailableReplicas: 1
