apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-provisioner

resources:
- nfs-provisioner-ns.yaml
- nfs-provisioner-role-binding.yaml
- github.com/kubernetes-sigs/nfs-subdir-external-provisioner/deploy

patches:
- path: nfs-provisioner-patch.yaml
