# Build stage
FROM registry.redhat.io/rhel9/go-toolset AS builder

USER 0
WORKDIR /opt/app-root/src

# Copy the source code into the container
COPY go.mod ./
RUN go mod download

COPY *.go ./

# Build the Go app
RUN go build -o main .

# Runtime stage
FROM registry.redhat.io/ubi9/ubi-minimal

WORKDIR /app

# Copy only the binary from the builder stage
COPY --from=builder /opt/app-root/src/main .

USER 1001

# Expose port 8080 to the outside world
EXPOSE 8080
 
# Command to run the executable
CMD ["./main"]
