apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: test-lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - fstype: xfs
        name: vg1
        thinPoolConfig:
          chunkSizeCalculationPolicy: Static
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lvm-block-1 
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block 
  resources:
    requests:
      storage: 1Gi 
  storageClassName: lvms-vg1           
---
kind: Pod
apiVersion: v1
metadata:
  name: test-lvm
  namespace: test
spec:
  restartPolicy: Always
#  serviceAccountName: test
  securityContext:
    seLinuxOptions:
      level: 's0:c28,c17'
    fsGroup: 1000790000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: test-shite
      command: 
        - "/bin/bash"
        - "-xc"
        - "/bin/dd if=/dev/block of=/dev/null bs=1K count=10; sleep 600"
      securityContext:
        capabilities:
          drop:
            - ALL
        privileged: false
        runAsUser: 1000790000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      imagePullPolicy: IfNotPresent
      volumeDevices:
      - devicePath: /dev/block
        name: content
      terminationMessagePolicy: File
      image: 'registry.redhat.io/rhel8/support-tools:latest'
#  serviceAccount: test
  volumes:
    - name: content
      persistentVolumeClaim:
        claimName: lvm-block-1  