apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lvm-filesystem-1 
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem 
  resources:
    requests:
      storage: 1Gi 
  storageClassName: lvms-vg1           
---
kind: Pod
apiVersion: v1
metadata:
  name: test-lvm-2
  namespace: test
spec:
  restartPolicy: Always
#  serviceAccountName: test
  securityContext:
    seLinuxOptions:
      level: 's0:c28,c17'
    fsGroup: 1000790000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: test-shite
      command: 
        - "/bin/bash"
        - "-xc"
        - "/bin/dd if=/dev/block of=/dev/null bs=1K count=10; sleep 600"
      securityContext:
        capabilities:
          drop:
            - ALL
        privileged: false
        runAsUser: 1000790000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: content
          mountPath: /mnt/data
      terminationMessagePolicy: File
      image: 'registry.redhat.io/rhel8/support-tools:latest'
#  serviceAccount: test
  volumes:
    - name: content
      persistentVolumeClaim:
        claimName: lvm-filesystem-1  