apiVersion: v1
kind: ConfigMap
metadata:
  name: htmlstuff
data:
  index.html: |
    <html>
    <head>
    <title>Hello OpenShift</title>
    </head>
    <body>
    <h4>Exciting</h4>
    <p>Really, really exciting!</p>
    </body>
    </html>
    
