apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd
  name: httpd
spec:
#  clusterIP: 172.30.210.215
#  clusterIPs:
#  - 172.30.210.215
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deployment: httpd
  sessionAffinity: None
  type: ClusterIP

