#
# Description: This is the 'internal-registry-redhat-io' kustomization file for the quay-mirror-config.
#               Specific files will extend/overlay/patch the files in this base.
#
# To view the output use:
#       oc kustomize ./base > ./generated/base.yaml
#
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Prefix all resources with the organisation anme
namePrefix: internal-registry-redhat-io-

resources:
  - ../base

patches:
  - target:
      kind: CronJob
      name: mirror
    patch: |-
      # Update the CronJob schedule so that it does not run at the same time as the other jobs
      - op: replace
        path: /spec/schedule
        # Run every 12 hours to capture any new repos
        value: "30 */12 * * *"

configMapGenerator:
  - name: quay-mirror-config
    behavior: merge

    literals:
      - NAMESPACE=internal-registry-redhat-io
      - DESTINATION_ROBOT=internal-registry-redhat-io+quay_mirror_cronjob 
      - SYNC_INTERVAL=7200
