apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patches:

- target:
    kind: ConsoleNotification
    name: cluster-description-banner
  patch: |-
    - op: replace
      path: /spec/backgroundColor
      value: '#BA00BA'
    - op: replace
      path: /spec/text
      value: 'Standby Management Hub cluster'
