
# Description: This ClusterRole is used by the Hub cluster (via a ServiceAccount)
#               to deploy configuration and applications to the DEVCS cluster
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-config-gitops
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - operators.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - operator.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - user.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - console.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  - persistentvolumeclaims
  - persistentvolumes
  - configmaps
  # Add standard Kubernetes application resources
  - services
  - pods
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - machine.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - compliance.openshift.io
  resources:
  - scansettingbindings
  verbs:
  - '*'
# The items below are in addition to the regular 'argocd-application-controller' ClusterRole
- apiGroups:
  - cert-manager.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - 'secrets'
  - 'resourcequotas'
  - 'serviceaccounts'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  - cronjobs/finalizers
  verbs:
  - '*'
- apiGroups:
  - platform.stackrox.io
  resources:
  - securedclusters
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
- apiGroups:
    - imageregistry.operator.openshift.io
  resources:
    - configs
  verbs:
    - '*'
- apiGroups:
    - logging.openshift.io
  resources:
    - clusterloggings
  verbs:
    - '*'
# Add standard Kubernetes resources
- verbs:
    - '*'
  apiGroups:
    - apps
  resources:
    - deployments
- verbs:
    - '*'
  apiGroups:
    - networking.k8s.io
  resources:
    - ingresses