apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-config-gitops-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-config-gitops
subjects:
- kind: ServiceAccount
  name: openshift-gitops-parent-sa
  namespace: cluster-config-gitops