apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: openshift-ingress
spec:
  commonName: "*.apps.9rr4l.dynamic.opentlc.com"
  dnsNames:
  - console-openshift-console.apps.9rr4l.dynamic.opentlc.com
  - oauth-openshift.apps.9rr4l.dynamic.opentlc.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ca-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: custom-certs-managed