kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: quay-db-backup
  namespace: quay
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: thin-csi
  volumeMode: Filesystem
