apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: acs-image-scan
spec:
  description: 'Scan an image with StackRox/RHACS This tasks allows you to return full vulnerability scan results for an image in JSON, CSV, or Pretty format. It''s a companion to the stackrox-image-check task, which checks an image against build-time policies.'
  params:
    - description: |
        The address:port tuple for StackRox Central
        (example - rox.stackrox.io:443)
      name: rox_central_endpoint
      type: string
    - description: Secret containing the StackRox API token with CI permissions
      name: rox_api_token
      type: string
    - description: |
        Full name of image to scan (example -- gcr.io/rox/sample:5.0-rc1)
      name: image
      type: string
    - description: The name of the cluster to run the image scan
      name: cluster
      type: string
    - default: table
      description: Output format (table | json | csv | sarif)
      name: output_format
      type: string
    - default: 'false'
      description: |
        When set to `"true"`, skip verifying the TLS certs of the Central
        endpoint.  Defaults to `"false"`.
      name: insecure-skip-tls-verify
      type: string
  steps:
    - name: rox-image-scan
      env:
        - name: ROX_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: rox_api_token
              name: $(params.rox_api_token)
        - name: ROX_CENTRAL_ENDPOINT
          value: 'acs-central.apps.hub-sdc.mgmt.cicz.gov.au:443'
        - name: IMAGE
          value: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -xe
        roxctl image scan \
        --endpoint $(params.rox_central_endpoint) \
        --insecure-skip-tls-verify=$(params.insecure-skip-tls-verify) \
        --output=$(params.output_format) \
        --image=$(params.image) \
        --cluster=$(params.cluster)
#        --token-file=/token/rox_api_token 
      computeResources: {}
      image: 'registry.redhat.io/advanced-cluster-security/rhacs-roxctl-rhel8:4.7'
