kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipeline-test-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-csi
  volumeMode: Filesystem
