apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: read-stuff
  namespace: test
spec:
  description: 'Read file from a PVC'
  params:
    - default: stuff.txt
      description: 'Filename to read from'
      name: input_file
      type: string
    - description: 'The image to use for the container'
      name: image 
      type: string
  steps:
    - name: read
      script: |
        #!/usr/bin/env bash
        set -xe
        ls -l $(workspaces.messages.path)        
        CONTENTS=$(cat $(workspaces.messages.path)/$(params.input_file))
        echo ${CONTENTS}
        if [ "${CONTENTS}" = "FAIL" ]; then
          exit 1
        fi        
      computeResources: {}
      image: $(params.image)
  workspaces:
    - name: messages    
      mountPath: /messages