kind: Namespace
apiVersion: v1
metadata:
  name: test
  annotations:
    argocd.argoproj.io/sync-wave: '-1'  
    operator.tekton.dev/prune.resources: "taskrun, pipelinerun"
    operator.tekton.dev/prune.keep: "2"