kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace-app-1
spec:
  # Applies to all pods in this namespace
  podSelector: 
    matchLabels:
      app: httpd-app-1  

  ingress:
  - from:
    # Allows ingress traffic from any pod in this same namespace
    - podSelector: 
        matchLabels:
          app: httpd-app-1  

  egress:
  - to:
    # Allows egress traffic to any pod in this same namespace
    - podSelector:
        matchLabels:
          app: httpd-app-1  

   # Allow access to OpenShift DNS
  - to:
      # Need to specify the openshift-dns pods to allow name resolution
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: openshift-dns
    ports:
      - protocol: TCP
        port: 5353
      - protocol: UDP
        port: 5353 

  policyTypes:
  - Ingress
  - Egress