apiVersion: v1
kind: ConfigMap
metadata:
  name: htmlstuff
  namespace: net-test-2  
data:
  index.html: |
    Hello from net-test-2
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd
    type: workload
  name: httpd
  namespace: net-test-2
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: httpd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: httpd
        type: workload
    spec:
      containers:
      - image: harbor.afp.le/openshift/ubi10/httpd-24:10.1-1778647163
        imagePullPolicy: Always
        name: httpd
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: htmlstuff
            mountPath: /var/www/html
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: htmlstuff
          configMap:
            name: htmlstuff
            items:
              - key: index.html
                path: index.html
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd
  name: httpd
  namespace: net-test-2  
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deployment: httpd
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: httpd
  name: httpds
  namespace: net-test-2  
spec:
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  to:
    kind: Service
    name: httpd
    weight: 100
  wildcardPolicy: None  