apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-aro-disk-storage-2
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#  storageClassName: disk-csi-ext
  storageClassName: managed-csi
  volumeMode: Filesystem    
---
kind: Pod
apiVersion: v1
metadata:
  name: test-aro-disk-storage-2
  namespace: test
spec:
  restartPolicy: Always
#  serviceAccountName: test
  securityContext:
    seLinuxOptions:
      level: 's0:c28,c17'
    fsGroup: 1000790000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: test-aro-storage
      command: 
        - "/bin/bash"
        - "-xc"
        - "sleep 600"
      securityContext:
        capabilities:
          drop:
            - ALL
        privileged: false
        runAsUser: 1000790000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: content
          mountPath: /data
#      volumeDevices:
#      - devicePath: /dev/block
#        name: content
      terminationMessagePolicy: File
      image: 'registry.redhat.io/rhel8/support-tools:latest'
#  serviceAccount: test
  volumes:
    - name: content
      persistentVolumeClaim:
        claimName: test-aro-disk-storage-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-aro-file-storage
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
#  storageClassName: disk-csi-ext
  storageClassName: file-csi-ext
  volumeMode: Filesystem    
---
kind: Pod
apiVersion: v1
metadata:
  name: test-aro-file-storage-1
  namespace: test
spec:
  restartPolicy: Always
#  serviceAccountName: test
  securityContext:
    seLinuxOptions:
      level: 's0:c28,c17'
    fsGroup: 1000790000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: test-aro-storage
      command: 
        - "/bin/bash"
        - "-xc"
        - "sleep 600"
      securityContext:
        capabilities:
          drop:
            - ALL
        privileged: false
        runAsUser: 1000790000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: content
          mountPath: /data
#      volumeDevices:
#      - devicePath: /dev/block
#        name: content
      terminationMessagePolicy: File
      image: 'registry.redhat.io/rhel8/support-tools:latest'
#  serviceAccount: test
  volumes:
    - name: content
      persistentVolumeClaim:
        claimName: test-aro-file-storage 
---
kind: Pod
apiVersion: v1
metadata:
  name: test-aro-file-storage-2
  namespace: test
spec:
  restartPolicy: Always
#  serviceAccountName: test
  securityContext:
    seLinuxOptions:
      level: 's0:c28,c17'
    fsGroup: 1000790000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: test-aro-storage
      command: 
        - "/bin/bash"
        - "-xc"
        - "sleep 600"
      securityContext:
        capabilities:
          drop:
            - ALL
        privileged: false
        runAsUser: 1000790000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: content
          mountPath: /data
#      volumeDevices:
#      - devicePath: /dev/block
#        name: content
      terminationMessagePolicy: File
      image: 'registry.redhat.io/rhel8/support-tools:latest'
#  serviceAccount: test
  volumes:
    - name: content
      persistentVolumeClaim:
        claimName: test-aro-file-storage         