apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert-good
  namespace: test
spec:
  commonName: bollocks.apps.disc.spenscot.ddns.net
  dnsNames:
    - bollocks.apps.disc.spenscot.ddns.net
  duration: "720h" # (30 days)
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ca-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: test-cert-good-managed
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert-bad
  namespace: test
spec:
  commonName: bollocks.apps.disc.spenscot.ddns.net
  dnsNames:
    - bollocks.apps.disc.spenscot.ddns.com
  duration: "720h" # (30 days)
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ca-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always    
  secretName: test-cert-bad-managed
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-validity-bad
  namespace: test
spec:
  commonName: bollocks.apps.disc.spenscot.ddns.net
  dnsNames:
    - bollocks.apps.disc.spenscot.ddns.net
  duration: "721h" # (30 days and 1 hour)
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ca-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always    
  secretName: test-cert-managed