apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  generation: 4
  labels:
    app: sso
  name: keycloak
  namespace: rh-keycloak
spec:
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  hostname:
    hostname: keycloak.apps.ocp4.spenscot.ddns.net
  http:
    tlsSecret: tls-certificate
  instances: 1
  additionalOptions:
    - name: log-level
      value: 'INFO,org.keycloak:TRACE'  