apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate
  namespace: rh-keycloak
spec:
  dnsNames:
  - keycloak.apps.spenscot.ddns.net
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: tls-certificate
  usages:
  - server auth