apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-12T03:41:27Z"
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    alertmanagerMain:
      enableUserAlertmanagerConfig: true
