apiVersion: batch/v1
kind: CronJob
metadata:
  name: vsphere-perm-test
  namespace: vsphere-perm-test
spec:
  schedule: 30 19 * * WED # UTC
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app: vsphere-perm-test
      name: vsphere-perm-test
    spec:
      backoffLimit: 0
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: vsphere-perm-test
        spec:
          containers:
          - command:
            - /bin/bash
            - -c
            - cd /opt/vsphere-perm-test && bash vsphere-perm-test.sh
            image: registry.redhat.io/openshift4/ose-cli:latest
            imagePullPolicy: IfNotPresent
            name: vsphere-perm-test
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /opt/vsphere-perm-test
              name: vsphere-perm-test
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          serviceAccount: vsphere-perm-test-sa
          serviceAccountName: vsphere-perm-test-sa
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 484
              name: vsphere-perm-test-config
            name: vsphere-perm-test
      ttlSecondsAfterFinished: 604800
  successfulJobsHistoryLimit: 1
  suspend: false
