apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: vsphere-checker-job-alert-rule
  namespace: vsphere-checker
spec:
  groups:
  - name: vsphere-checker-batch-job
    rules:
    - alert: VSphereCheckerJobSuccess
      annotations:
        description: The VSphere checker job was able to create a new node successfully
        summary: VSphere checker job success
      expr: kube_job_status_succeeded > 0
      labels:
        app: vsphere-checker
        severity: info
    - alert: VSphereCheckerJobFailure
      annotations:
        description: The VSphere checker job failed to create a new node in the cluster
        summary: VSphere checker job failed
      expr: kube_job_status_failed > 0
      labels:
        app: vsphere-checker
        severity: critical
