apiVersion: updateservice.operator.openshift.io/v1
kind: UpdateService
metadata:
  name: service
  namespace: openshift-update-service
spec:
  replicas: 1
  releases: harbor.spenscot.ddns.net/quay/openshift-release-dev
  graphDataImage: harbor.spenscot.ddns.net/openshift4/graph-data:latest