apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: quay-backups
  namespace: quay
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  generateBucketName: cnpg-backup
  objectBucketName: obc-openshift-operators-cnpg-backup
  storageClassName: openshift-storage.noobaa.io