apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"  
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"    
  name: quay-registry-quay-postgres
  namespace: quay
spec:
  instances: 3
  logLevel: info  

  # Ensure postgres pods run on different nodes
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    # Move the pod if a node becomes available again
    podAntiAffinityType: required

  storage:
    size: 50Gi

  # Create the empty Quay database
  #
  bootstrap:
    initdb:
      database: quay-registry-quay-database
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: quay-registry-quay-database

  # Enable WAL archiving to the Barman Cloud plugin
  plugins:
  - enabled: true
    isWALArchiver: true
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: quay-db-objectstore

  backup:
    target: prefer-standby
