FROM registry.redhat.io/ubi9/ubi:9.5

#COPY s3cmd-master /opt/s3cmd/

#RUN yum -y install python &&\
#    yum clean all

RUN yum -y install python git &&\
    git clone https://github.com/s3tools/s3cmd.git /opt/s3cmd &&\
    yum -y erase git &&\
    yum clean all &&\
    ln -s /opt/s3cmd/s3cmd /usr/bin/s3cmd

WORKDIR /opt

ADD ./src/s3cfg /opt/.s3cfg
ADD ./src/main.sh /opt/main.sh

# Main entrypoint script
RUN chmod 777 /opt/main.sh

# Folders for s3cmd optionations
RUN mkdir /opt/src
RUN mkdir /opt/dest

WORKDIR /
ENTRYPOINT ["/opt/main.sh"]
CMD ["s3cmd", "ls"]

