apiVersion: v1
kind: LimitRange
metadata:
  name: my-limit-range
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 1Gi
      defaultRequest:
        cpu: 250m
        memory: 256Mi
        