---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-collector
  namespace: openshift-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clog-collector-audit
subjects:
  - kind: ServiceAccount
    name: log-collector
    namespace: openshift-logging
roleRef:
  kind: ClusterRole
  name: collect-audit-logs
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clog-collector-application
subjects:
  - kind: ServiceAccount
    name: log-collector
    namespace: openshift-logging
roleRef:
  kind: ClusterRole
  name: collect-application-logs
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: log-collector-infrastructure
subjects:
  - kind: ServiceAccount
    name: log-collector
    namespace: openshift-logging
roleRef:
  kind: ClusterRole
  name: collect-infrastructure-logs
  apiGroup: rbac.authorization.k8s.io
---
#apiVersion: observability.openshift.io/v1
#kind: ClusterLogForwarder
#metadata:
#  name: instance-http
#  namespace: openshift-logging
#spec:
#  serviceAccountName: cluster-logging
#  outputs:
#    - http:
#        method: GET
#        schema: opentelemetry
#      name: remote-http
#      syslog:
#        rfc: RFC5424
#      type: http
#      url: 'http://192.168.41.13:8080'
#  pipelines:
#    - inputRefs:
#        - application
#        - audit
#        - infrastructure
#      name: enable-default-log-store
#      outputRefs:
#        - remote-http
#---
# Removed in 6.1
#apiVersion: logging.openshift.io/v1
#kind: ClusterLogging
#metadata:
#  name: instance-http
#  namespace: openshift-logging
#spec:
#  serviceAccountName: cluster-logging
#  collection:
#    type: vector
#### the vector config gets ignored
#    vector:
#      buffer:
#        max_events: 100000
#        type: memory
#        when_full: block
#      batch:
#        max_events: 100000
#        timeout_secs: 60
###
#    fluentd:
#      buffer:
#        retryType: periodic
#        flushMode: interval
#        flushInterval: 60s
#        chunkLimitSize: '100000'
#        overflowAction: block
#    type: fluentd
#    tolerations:
#      - key: node-role.kubernetes.io/master
#        effect: NoSchedule
#      - key: node-role.kubernetes.io/infra
#        value: reserved
#        effect: NoSchedule
#      - key: node-role.kubernetes.io/infra
#        value: reserved
#        effect: NoExecute